apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "basicwebapp.fullname" . }}
  namespace: {{ .Values.nameSpace }}
spec:
  secretName: {{ .Values.ingress.secretName }}
  issuerRef:
    name: {{ .Values.issuerRef }}
  commonName: {{ .Values.ingress.hosts }}
  dnsNames:
  - {{ .Values.ingress.hosts }}
  acme:
    config:
    - http01:
        ingress: {{ .Values.ingress.ingressName }}
      domains:
      - {{ .Values.ingress.hosts }}
